-- Word → icon mapping for quick action suggestion chips
-- Split suggestion text into words and look each word up.
-- The first word that resolves wins; you can also combine verb+noun.

local WORD_ICONS = {
    -- === VERBS ===
    open        = "lock-open.png",
    close       = "door-closed.png",
    shut        = "door-closed.png",
    lock        = "lock.png",
    unlock      = "lock-open.png",
    look        = "eye.png",
    examine     = "magnifying-glass.png",
    inspect     = "magnifying-glass.png",
    search      = "magnifying-glass.png",
    read        = "book-open.png",
    take        = "hand.png",
    grab        = "hand.png",
    pick        = "hand.png",
    get         = "hand.png",
    drop        = "hand.png",
    put         = "hand.png",
    place       = "hand.png",
    inventory   = "backpack.png",
    use         = "magic-wand.png",
    equip       = "sword.png",
    wear        = "helmet.png",
    attack      = "sword.png",
    fight       = "axe.png",
    hit         = "fist.png",
    strike      = "axe.png",
    kill        = "skull.png",
    cast        = "spellbook.png",
    drink       = "health-potion.png",
    eat         = "apple.png",
    light       = "candle.png",
    burn        = "campfire.png",
    extinguish  = "candle.png",
    climb       = "rope.png",
    go          = "footprints.png",
    enter       = "door-open.png",
    exit        = "door-open.png",
    leave       = "footprints.png",
    north       = "compass.png",
    south       = "compass.png",
    east        = "compass.png",
    west        = "compass.png",
    up          = "compass.png",
    down        = "compass.png",
    move        = "footprints.png",
    push        = "hand-plane.png",
    pull        = "rope.png",
    dig         = "shovel.png",
    cut         = "axe.png",
    chop        = "axe.png",
    ['break']   = "anvil-hammer.png",
    smash       = "anvil-hammer.png",
    fix         = "gear.png",
    repair      = "gear.png",
    buy         = "coin.png",
    sell        = "money-bag.png",
    trade       = "handshake.png",
    give        = "handshake.png",
    ask         = "question.png",
    tell        = "speak.png",
    listen      = "ear.png",
    wait        = "hourglass.png",
    rest        = "bedroll.png",
    sleep       = "sleepy.png",
    pray        = "star.png",
    fish        = "fishing-rod.png",
    row         = "paddles.png",
    sail        = "ship.png",
    save        = "scroll-seal.png",
    load        = "journal.png",
    help        = "help.png",
    hint        = "idea.png",
    score       = "star.png",
    think       = "thinking.png",
    craft       = "anvil-hammer.png",
    brew        = "cauldron.png",
    mix         = "mortar-pestle.png",
    play        = "playing-card.png",
    throw       = "fist.png",
    shoot       = "bow.png",
    collect     = "satchel.png",
    fill        = "cauldron.png",
    pour        = "green-potion.png",
    whistle     = "horn.png",

    -- === NOUNS — objects ===
    door        = "door-closed.png",
    gate        = "door-dungeon.png",
    chest       = "treasure-chest.png",
    box         = "crate.png",
    crate       = "crate.png",
    bag         = "coin-pouch.png",
    sack        = "satchel.png",
    backpack    = "backpack.png",
    pouch       = "coin-pouch.png",
    key         = "key.png",
    -- lock        = "lock.png",
    sword       = "sword.png",
    blade       = "sword.png",
    axe         = "axe.png",
    bow         = "bow.png",
    shield      = "shield.png",
    helmet      = "helmet.png",
    armor       = "knight-helmet.png",
    armour      = "knight-helmet.png",
    wand        = "magic-wand.png",
    staff       = "magic-wand.png",
    spellbook   = "spellbook.png",
    book        = "book-open.png",
    tome        = "spellbook.png",
    scroll      = "scroll-seal.png",
    map         = "map.png",
    compass     = "compass.png",
    lantern     = "lantern.png",
    torch       = "candle.png",
    candle      = "candle.png",
    rope        = "rope.png",
    shovel      = "shovel.png",
    pickaxe     = "pickaxe.png",
    saw         = "saw.png",
    hammer      = "anvil-hammer.png",
    anvil       = "anvil-hammer.png",
    gear        = "gear.png",
    potion      = "health-potion.png",
    vial        = "green-potion.png",
    -- brew        = "cauldron.png",
    apple       = "apple.png",
    food        = "apple.png",
    grapes      = "grapes.png",
    mushroom    = "mushroom.png",
    wheat       = "wheat.png",
    flower      = "flower.png",
    coin        = "coin.png",
    gold        = "coin.png",
    money       = "money-bag.png",
    gem         = "gem.png",
    jewel       = "gem.png",
    crystal     = "crystal-ball.png",
    orb         = "crystal-ball.png",
    trophy      = "crown.png",
    crown       = "crown.png",
    banner      = "banner.png",
    crest       = "crest-shield.png",
    dice        = "dice.png",
    card        = "playing-card.png",
    harp        = "harp.png",
    lute        = "lute.png",
    drum        = "drum.png",
    horn        = "horn.png",
    quill       = "quill.png",
    journal     = "journal.png",
    telescope   = "telescope.png",
    hourglass   = "hourglass.png",
    boat        = "paddles.png",
    ship        = "ship.png",
    tent        = "tent.png",
    bedroll     = "bedroll.png",
    safe        = "safe.png",
    bones       = "bones.png",
    skull       = "skull.png",
    horseshoe   = "horseshoe.png",
    fishing     = "fishing-rod.png",
    rod         = "fishing-rod.png",

    -- === NOUNS — places / scenery ===
    bridge      = "bridge.png",
    well        = "well.png",
    fire        = "campfire.png",
    campfire    = "campfire.png",
    firepit     = "fire-pit.png",
    tree        = "tree.png",
    forest      = "tree.png",
    cave        = "door-dungeon.png",
    dungeon     = "door-dungeon.png",
    market      = "market-stall.png",
    shop        = "market-stall.png",
    stall       = "market-stall.png",
    signpost    = "signpost.png",
    sign        = "signpost.png",
    pin         = "location-pin.png",
    location    = "location-pin.png",
    logs        = "logs.png",
    log         = "logs.png",
    cloud       = "cloud.png",
    rain        = "rain-cloud.png",
    snow        = "snowflake.png",
    wind        = "wind.png",
    tornado     = "tornado.png",
    lightning   = "lightning.png",
    rainbow     = "rainbow.png",
    moon        = "moon.png",
    sun         = "sun.png",

    -- === NOUNS — creatures / characters ===
    dragon      = "dragon.png",
    goblin      = "goblin.png",
    ghost       = "ghost.png",
    slime       = "slime.png",
    wizard      = "wizard.png",
    rogue       = "rogue.png",
    knight      = "chess-knight.png",
    princess    = "princess.png",
    meeple      = "meeple.png",
    person      = "person.png",
    group       = "group.png",
    merchant    = "market-stall.png",

    -- === ABSTRACT / UI ===
    quest       = "quest.png",
    mission     = "quest.png",
    objective   = "quest.png",
    -- hint        = "idea.png",
    idea        = "idea.png",
    -- help        = "help.png",
    question    = "question.png",
    alert       = "alert.png",
    warning     = "alert.png",
    chat        = "chat.png",
    talk        = "talk.png",
    speak       = "speak.png",
    happy       = "happy.png",
    angry       = "angry.png",
    surprised   = "surprised.png",
    thinking    = "thinking.png",
    star        = "star.png",
    heart       = "heart.png",
    health      = "health-potion.png",
}

-- Resolve an icon for a suggestion string like "open chest" or "talk to merchant"
-- Returns the icon filename, or nil if nothing matched.
local STOP_WORDS = {
    a=true, an=true, the=true, to=true, at=true,
    with=true, into=true, on=true, ["in"]=true, of=true,
    from=true, ["and"]=true, your=true, my=true,
}

return function(text)
    local words = {}
    for w in text:lower():gmatch("%a+") do
        if not STOP_WORDS[w] then
            words[#words+1] = w
        end
    end
    -- Verb wins over noun: try words in order, first match wins.
    for _, w in ipairs(words) do
        if WORD_ICONS[w] then
            return WORD_ICONS[w]
        end
    end
    return nil  -- no icon; caller can show a generic fallback
end